openapi: 3.0.0
info:
  title: Flight Velocity Modeling API
  description: API for getting flight velocity data
  version: 1.0.0
paths:
  /flight-velocity:
    get:
      summary: Get Flight Velocity Data
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
